class MaterialsData {
  static List<String> branches = [
    'Kardiyoloji',
    'Nöroloji',
    'Gastroenteroloji',
    'Endokrinoloji',
    'Nefroloji',
    'Göğüs Hastalıkları',
    'Hematoloji',
    'Romatoloji',
    'Enfeksiyon Hastalıkları',
    'Onkoloji',
    'Dermatoloji',
    'Fizik Tedavi ve Rehabilitasyon',
    'Psikiyatri',
    'Genel Cerrahi',
    'Ortopedi',
    'Üroloji',
    'Göz Hastalıkları',
    'KBB',
    'Kadın Hastalıkları ve Doğum',
    'Radyoloji',
    'Anesteziyoloji',
    'Acil Tıp',
    'Aile Hekimliği',
    'Çocuk Sağlığı ve Hastalıkları',
  ];

  static Map<String, List<String>> branchTextbooks = {
    'Kardiyoloji': [
      'Braunwald\'s Heart Disease',
      'Hurst\'s The Heart',
      'Mayo Clinic Cardiology',
    ],
    'Nöroloji': [
      'Adams and Victor\'s Principles of Neurology',
      'Bradley\'s Neurology',
      'Merritt\'s Neurology',
    ],
    'Gastroenteroloji': [
      'Sleisenger and Fordtran\'s GI',
      'Yamada\'s Textbook of Gastroenterology',
    ],
    'Endokrinoloji': [
      'Williams Textbook of Endocrinology',
      'Greenspan\'s Basic & Clinical Endocrinology',
    ],
    'Nefroloji': [
      'Brenner & Rector\'s The Kidney',
      'Comprehensive Clinical Nephrology',
    ],
    'Göğüs Hastalıkları': [
      'Murray & Nadel\'s Textbook of Respiratory Medicine',
      'Fishman\'s Pulmonary Diseases and Disorders',
    ],
    'Hematoloji': [
      'Williams Hematology',
      'Wintrobe\'s Clinical Hematology',
    ],
    'Romatoloji': [
      'Kelley and Firestein\'s Textbook of Rheumatology',
      'Hochberg\'s Rheumatology',
    ],
    'Enfeksiyon Hastalıkları': [
      'Mandell, Douglas, and Bennett\'s Infectious Disease',
      'Principles and Practice of Infectious Diseases',
    ],
    'Onkoloji': [
      'DeVita, Hellman, and Rosenberg\'s Cancer',
      'Abeloff\'s Clinical Oncology',
    ],
    'Dermatoloji': [
      'Fitzpatrick\'s Dermatology',
      'Andrews\' Diseases of the Skin',
    ],
    'Fizik Tedavi ve Rehabilitasyon': [
      'DeLisa\'s Physical Medicine and Rehabilitation',
      'Braddom\'s Physical Medicine and Rehabilitation',
    ],
    'Psikiyatri': [
      'Kaplan & Sadock\'s Comprehensive Textbook of Psychiatry',
      'The American Psychiatric Association Publishing Textbook of Psychiatry',
    ],
    'Genel Cerrahi': [
      'Sabiston Textbook of Surgery',
      'Schwartz\'s Principles of Surgery',
    ],
    'Ortopedi': [
      'Campbell\'s Operative Orthopaedics',
      'Rockwood and Green\'s Fractures in Adults',
    ],
    'Üroloji': [
      'Campbell-Walsh Urology',
      'Smith and Tanagho\'s General Urology',
    ],
    'Göz Hastalıkları': [
      'Vaughan & Asbury\'s General Ophthalmology',
      'Kanski\'s Clinical Ophthalmology',
    ],
    'KBB': [
      'Cummings Otolaryngology',
      'Bailey\'s Head and Neck Surgery',
    ],
    'Kadın Hastalıkları ve Doğum': [
      'Williams Obstetrics',
      'Berek & Novak\'s Gynecology',
    ],
    'Radyoloji': [
      'Brant and Helms\' Fundamentals of Diagnostic Radiology',
      'Grainger & Allison\'s Diagnostic Radiology',
    ],
    'Anesteziyoloji': [
      'Miller\'s Anesthesia',
      'Morgan & Mikhail\'s Clinical Anesthesiology',
    ],
    'Acil Tıp': [
      'Tintinalli\'s Emergency Medicine',
      'Rosen\'s Emergency Medicine',
    ],
    'Aile Hekimliği': [
      'Rakel & Rakel\'s Textbook of Family Medicine',
      'Taylor\'s Family Medicine',
    ],
    'Çocuk Sağlığı ve Hastalıkları': [
      'Nelson Textbook of Pediatrics',
      'Rudolph\'s Pediatrics',
    ],
  };

  static Map<String, List<String>> textbookChapters = {
    'Braunwald\'s Heart Disease': [
      'Chapter 1: Fundamentals of Cardiovascular Disease',
      'Chapter 2: Genetics and Personalized Medicine',
      'Chapter 3: Evaluation of the Patient',
      'Chapter 4: Heart Failure',
      'Chapter 5: Arrhythmias',
      'Chapter 6: Preventive Cardiology',
      'Chapter 7: Coronary Heart Disease',
      'Chapter 8: Valvular Heart Disease',
      'Chapter 9: Hypertension',
      'Chapter 10: Pulmonary Hypertension',
    ],
    'Hurst\'s The Heart': [
      'Chapter 1: Cardiovascular Disease',
      'Chapter 2: Physical Examination',
      'Chapter 3: Electrocardiography',
      'Chapter 4: Imaging Techniques',
      'Chapter 5: Heart Sounds and Murmurs',
      'Chapter 6: Cardiac Catheterization',
      'Chapter 7: Coronary Arteriography',
      'Chapter 8: Myocardial Diseases',
    ],
    'Mayo Clinic Cardiology': [
      'Basic ECG Interpretation',
      'Advanced ECG Analysis',
      'Cardiac Imaging',
      'Clinical Cases in Cardiology',
      'Cardiovascular Testing',
      'Management of Acute Cardiac Conditions',
      'Preventive Cardiology Strategies',
    ],
    'Adams and Victor\'s Principles of Neurology': [
      'Chapter 1: Neurologic Assessment',
      'Chapter 2: Imaging Studies',
      'Chapter 3: Headache and Other Craniofacial Pain',
      'Chapter 4: Disorders of Movement',
      'Chapter 5: Disorders of the Spinal Cord',
      'Chapter 6: Cerebrovascular Diseases',
      'Chapter 7: Neoplasms of the Nervous System',
      'Chapter 8: Infections of the Nervous System',
      'Chapter 9: Multiple Sclerosis',
      'Chapter 10: Epilepsy and Other Seizure Disorders',
    ],
    'Bradley\'s Neurology': [
      'Chapter 1: Neurological Investigation',
      'Chapter 2: Stroke',
      'Chapter 3: Epilepsy',
      'Chapter 4: Movement Disorders',
      'Chapter 5: Neuromuscular Diseases',
      'Chapter 6: Neuroimmunology',
      'Chapter 7: Sleep Disorders',
      'Chapter 8: Neuro-oncology',
    ],
    'Merritt\'s Neurology': [
      'Chapter 1: Movement Disorders',
      'Chapter 2: Dementia',
      'Chapter 3: Cerebrovascular Disease',
      'Chapter 4: Neurological Infections',
      'Chapter 5: Neuromuscular Disorders',
      'Chapter 6: Neurological Emergencies',
      'Chapter 7: Neurorehabilitation',
    ],
    'Sleisenger and Fordtran\'s GI': [
      'Chapter 1: Gastrointestinal Endoscopy',
      'Chapter 2: Esophageal Disorders',
      'Chapter 3: Liver Disease',
      'Chapter 4: Inflammatory Bowel Disease',
      'Chapter 5: Pancreatic Disorders',
      'Chapter 6: GI Bleeding',
      'Chapter 7: Motility Disorders',
      'Chapter 8: Nutrition in GI Disease',
    ],
    'Yamada\'s Textbook of Gastroenterology': [
      'Chapter 1: Upper GI Tract',
      'Chapter 2: Lower GI Tract',
      'Chapter 3: Hepatology',
      'Chapter 4: Biliary System',
      'Chapter 5: Pancreas',
      'Chapter 6: GI Oncology',
      'Chapter 7: Functional GI Disorders',
    ],
    'Williams Textbook of Endocrinology': [
      'Chapter 1: Hypothalamus and Pituitary',
      'Chapter 2: Thyroid',
      'Chapter 3: Diabetes Mellitus',
      'Chapter 4: Adrenal Disorders',
      'Chapter 5: Reproductive Endocrinology',
      'Chapter 6: Metabolic Bone Disease',
      'Chapter 7: Obesity and Nutrition',
      'Chapter 8: Endocrine Neoplasia',
    ],
    'Greenspan\'s Basic & Clinical Endocrinology': [
      'Chapter 1: Adrenal Disorders',
      'Chapter 2: Reproductive Endocrinology',
      'Chapter 3: Thyroid Disease',
      'Chapter 4: Calcium Disorders',
      'Chapter 5: Endocrine Hypertension',
      'Chapter 6: Diabetes Management',
      'Chapter 7: Growth Disorders',
    ],
    'Brenner & Rector\'s The Kidney': [
      'Chapter 1: Anatomy and Physiology',
      'Chapter 2: Clinical Evaluation',
      'Chapter 3: Acute Kidney Injury',
      'Chapter 4: Chronic Kidney Disease',
      'Chapter 5: Glomerular Diseases',
      'Chapter 6: Hypertension',
      'Chapter 7: Electrolyte Disorders',
      'Chapter 8: Kidney Transplantation',
    ],
    'Comprehensive Clinical Nephrology': [
      'Chapter 1: Chronic Kidney Disease',
      'Chapter 2: Glomerular Diseases',
      'Chapter 3: Fluid and Electrolytes',
      'Chapter 4: Dialysis',
      'Chapter 5: Transplantation',
      'Chapter 6: Hypertension',
      'Chapter 7: Genetic Kidney Diseases',
    ],
    'Murray & Nadel\'s Textbook of Respiratory Medicine': [
      'Chapter 1: Pulmonary Function',
      'Chapter 2: Asthma',
      'Chapter 3: COPD',
      'Chapter 4: Interstitial Lung Disease',
      'Chapter 5: Pulmonary Infections',
      'Chapter 6: Lung Cancer',
      'Chapter 7: Sleep Medicine',
      'Chapter 8: Critical Care',
    ],
    'Fishman\'s Pulmonary Diseases and Disorders': [
      'Chapter 1: Clinical Assessment',
      'Chapter 2: Respiratory Infections',
      'Chapter 3: Obstructive Lung Disease',
      'Chapter 4: Occupational Lung Disease',
      'Chapter 5: Pulmonary Vascular Disease',
      'Chapter 6: Respiratory Failure',
      'Chapter 7: Environmental Lung Disease',
    ],
    'Williams Hematology': [
      'Chapter 1: Clinical Hematology',
      'Chapter 2: Anemias',
      'Chapter 3: Leukemias',
      'Chapter 4: Lymphomas',
      'Chapter 5: Coagulation Disorders',
      'Chapter 6: Transfusion Medicine',
      'Chapter 7: Bone Marrow Disorders',
      'Chapter 8: Myeloproliferative Disorders',
    ],
    'Wintrobe\'s Clinical Hematology': [
      'Chapter 1: Red Blood Cell Disorders',
      'Chapter 2: White Blood Cell Disorders',
      'Chapter 3: Platelet Disorders',
      'Chapter 4: Hemostasis and Thrombosis',
      'Chapter 5: Hematologic Malignancies',
      'Chapter 6: Stem Cell Transplantation',
      'Chapter 7: Plasma Cell Disorders',
    ],
    'Kelley and Firestein\'s Textbook of Rheumatology': [
      'Chapter 1: Basic Principles of Rheumatology',
      'Chapter 2: Rheumatoid Arthritis',
      'Chapter 3: Systemic Lupus Erythematosus',
      'Chapter 4: Spondyloarthropathies',
      'Chapter 5: Vasculitis',
      'Chapter 6: Crystal Arthropathies',
      'Chapter 7: Osteoarthritis',
      'Chapter 8: Systemic Sclerosis',
    ],
    'Hochberg\'s Rheumatology': [
      'Chapter 1: Clinical Assessment',
      'Chapter 2: Autoimmune Diseases',
      'Chapter 3: Inflammatory Arthritis',
      'Chapter 4: Metabolic Bone Disease',
      'Chapter 5: Soft Tissue Rheumatism',
      'Chapter 6: Pediatric Rheumatology',
      'Chapter 7: Rehabilitation in Rheumatic Diseases',
    ],
    'Mandell, Douglas, and Bennett\'s Infectious Disease': [
      'Chapter 1: Basic Principles of Infectious Diseases',
      'Chapter 2: Bacterial Infections',
      'Chapter 3: Viral Infections',
      'Chapter 4: Fungal Infections',
      'Chapter 5: Parasitic Diseases',
      'Chapter 6: HIV/AIDS',
      'Chapter 7: Tropical Medicine',
      'Chapter 8: Healthcare-Associated Infections',
    ],
    'Principles and Practice of Infectious Diseases': [
      'Chapter 1: Clinical Microbiology',
      'Chapter 2: Anti-infective Therapy',
      'Chapter 3: Respiratory Tract Infections',
      'Chapter 4: Bloodstream Infections',
      'Chapter 5: CNS Infections',
      'Chapter 6: Gastrointestinal Infections',
      'Chapter 7: Emerging Infectious Diseases',
    ],
    'DeVita, Hellman, and Rosenberg\'s Cancer': [
      'Chapter 1: Cancer Biology',
      'Chapter 2: Cancer Therapeutics',
      'Chapter 3: Solid Tumors',
      'Chapter 4: Hematologic Malignancies',
      'Chapter 5: Cancer Prevention',
      'Chapter 6: Cancer Genetics',
      'Chapter 7: Immunotherapy',
      'Chapter 8: Supportive Care in Cancer',
    ],
    'Abeloff\'s Clinical Oncology': [
      'Chapter 1: Principles of Oncology',
      'Chapter 2: Diagnostic Imaging',
      'Chapter 3: Medical Oncology',
      'Chapter 4: Radiation Oncology',
      'Chapter 5: Surgical Oncology',
      'Chapter 6: Cancer Emergencies',
      'Chapter 7: Palliative Care',
    ],
    'Fitzpatrick\'s Dermatology': [
      'Chapter 1: Basic Science of Skin',
      'Chapter 2: Clinical Dermatology',
      'Chapter 3: Inflammatory Conditions',
      'Chapter 4: Skin Infections',
      'Chapter 5: Skin Cancers',
      'Chapter 6: Pediatric Dermatology',
      'Chapter 7: Cosmetic Dermatology',
      'Chapter 8: Hair and Nail Disorders',
    ],
    'Andrews\' Diseases of the Skin': [
      'Chapter 1: Skin Examination',
      'Chapter 2: Papulosquamous Disorders',
      'Chapter 3: Vesiculobullous Diseases',
      'Chapter 4: Pigmentation Disorders',
      'Chapter 5: Adnexal Disorders',
      'Chapter 6: Cutaneous Manifestations',
      'Chapter 7: Dermatologic Surgery',
    ],
    'DeLisa\'s Physical Medicine and Rehabilitation': [
      'Chapter 1: Principles of Rehabilitation Medicine',
      'Chapter 2: Musculoskeletal Rehabilitation',
      'Chapter 3: Neurological Rehabilitation',
      'Chapter 4: Cardiac Rehabilitation',
      'Chapter 5: Pulmonary Rehabilitation',
      'Chapter 6: Pain Management',
      'Chapter 7: Prosthetics and Orthotics',
      'Chapter 8: Sports Medicine',
    ],
    'Braddom\'s Physical Medicine and Rehabilitation': [
      'Chapter 1: Physical Examination',
      'Chapter 2: Electrodiagnosis',
      'Chapter 3: Therapeutic Exercise',
      'Chapter 4: Spinal Cord Injury',
      'Chapter 5: Stroke Rehabilitation',
      'Chapter 6: Orthopedic Rehabilitation',
      'Chapter 7: Pediatric Rehabilitation',
    ],
    'Kaplan & Sadock\'s Comprehensive Textbook of Psychiatry': [
      'Chapter 1: Neural Sciences',
      'Chapter 2: Psychopathology',
      'Chapter 3: Clinical Psychiatry',
      'Chapter 4: Mood Disorders',
      'Chapter 5: Anxiety Disorders',
      'Chapter 6: Schizophrenia',
      'Chapter 7: Personality Disorders',
      'Chapter 8: Child Psychiatry',
    ],
    'The American Psychiatric Association Publishing Textbook of Psychiatry': [
      'Chapter 1: Psychiatric Assessment',
      'Chapter 2: Psychopharmacology',
      'Chapter 3: Psychotherapy',
      'Chapter 4: Substance Use Disorders',
      'Chapter 5: Neurocognitive Disorders',
      'Chapter 6: Consultation-Liaison Psychiatry',
      'Chapter 7: Emergency Psychiatry',
    ],
    'Sabiston Textbook of Surgery': [
      'Chapter 1: Basic Surgical Principles',
      'Chapter 2: Preoperative Management',
      'Chapter 3: Postoperative Care',
      'Chapter 4: Trauma and Emergency Surgery',
      'Chapter 5: Gastrointestinal Surgery',
      'Chapter 6: Surgical Oncology',
      'Chapter 7: Vascular Surgery',
      'Chapter 8: Transplantation',
    ],
    'Schwartz\'s Principles of Surgery': [
      'Chapter 1: Surgical Basic Science',
      'Chapter 2: Perioperative Care',
      'Chapter 3: Surgical Infections',
      'Chapter 4: Trauma',
      'Chapter 5: Abdominal Surgery',
      'Chapter 6: Breast Surgery',
      'Chapter 7: Endocrine Surgery',
      'Chapter 8: Pediatric Surgery',
    ],
    'Campbell\'s Operative Orthopaedics': [
      'Chapter 1: General Principles',
      'Chapter 2: Trauma',
      'Chapter 3: Sports Medicine',
      'Chapter 4: Arthroplasty',
      'Chapter 5: Spine Surgery',
      'Chapter 6: Hand Surgery',
      'Chapter 7: Pediatric Orthopaedics',
      'Chapter 8: Musculoskeletal Tumors',
    ],
    'Rockwood and Green\'s Fractures in Adults': [
      'Chapter 1: Fracture Management',
      'Chapter 2: Upper Extremity Fractures',
      'Chapter 3: Lower Extremity Fractures',
      'Chapter 4: Pelvic Fractures',
      'Chapter 5: Spine Fractures',
      'Chapter 6: Complications',
      'Chapter 7: Rehabilitation',
    ],
    'Campbell-Walsh Urology': [
      'Chapter 1: Basic Science',
      'Chapter 2: Urologic Evaluation',
      'Chapter 3: Urologic Infections',
      'Chapter 4: Urologic Oncology',
      'Chapter 5: Stone Disease',
      'Chapter 6: Voiding Dysfunction',
      'Chapter 7: Male Infertility',
      'Chapter 8: Pediatric Urology',
    ],
    'Smith and Tanagho\'s General Urology': [
      'Chapter 1: Clinical Urology',
      'Chapter 2: Urodynamics',
      'Chapter 3: Prostate Diseases',
      'Chapter 4: Urinary Tract Infections',
      'Chapter 5: Urologic Emergencies',
      'Chapter 6: Sexual Dysfunction',
      'Chapter 7: Reconstructive Urology',
    ],
    'Vaughan & Asbury\'s General Ophthalmology': [
      'Chapter 1: Anatomy and Embryology',
      'Chapter 2: Optics and Refraction',
      'Chapter 3: Lens and Cataract',
      'Chapter 4: Retinal Disorders',
      'Chapter 5: Glaucoma',
      'Chapter 6: Neuro-ophthalmology',
      'Chapter 7: Ocular Trauma',
      'Chapter 8: Pediatric Ophthalmology',
    ],
    'Kanski\'s Clinical Ophthalmology': [
      'Chapter 1: Eyelids and Orbit',
      'Chapter 2: Cornea and External Eye',
      'Chapter 3: Uveitis',
      'Chapter 4: Medical Retina',
      'Chapter 5: Surgical Retina',
      'Chapter 6: Strabismus',
      'Chapter 7: Ocular Oncology',
    ],
    'Cummings Otolaryngology': [
      'Chapter 1: Basic Science',
      'Chapter 2: Head and Neck Surgery',
      'Chapter 3: Laryngology',
      'Chapter 4: Rhinology',
      'Chapter 5: Otology',
      'Chapter 6: Facial Plastic Surgery',
      'Chapter 7: Pediatric Otolaryngology',
      'Chapter 8: Sleep Medicine',
    ],
    'Bailey\'s Head and Neck Surgery': [
      'Chapter 1: Clinical Assessment',
      'Chapter 2: Oral Cavity',
      'Chapter 3: Pharynx and Esophagus',
      'Chapter 4: Nose and Paranasal Sinuses',
      'Chapter 5: Ear Surgery',
      'Chapter 6: Neck Masses',
      'Chapter 7: Reconstructive Surgery',
    ],
    'Williams Obstetrics': [
      'Chapter 1: Maternal Anatomy',
      'Chapter 2: Prenatal Care',
      'Chapter 3: Normal Labor',
      'Chapter 4: Obstetric Complications',
      'Chapter 5: Maternal-Fetal Medicine',
      'Chapter 6: Operative Obstetrics',
      'Chapter 7: Postpartum Care',
      'Chapter 8: Obstetric Anesthesia',
    ],
    'Berek & Novak\'s Gynecology': [
      'Chapter 1: Basic Science',
      'Chapter 2: Benign Gynecology',
      'Chapter 3: Gynecologic Oncology',
      'Chapter 4: Reproductive Endocrinology',
      'Chapter 5: Urogynecology',
      'Chapter 6: Family Planning',
      'Chapter 7: Minimally Invasive Surgery',
    ],
    'Brant and Helms\' Fundamentals of Diagnostic Radiology': [
      'Chapter 1: Physics and Protection',
      'Chapter 2: Chest Radiology',
      'Chapter 3: Cardiac Imaging',
      'Chapter 4: Gastrointestinal Radiology',
      'Chapter 5: Genitourinary Radiology',
      'Chapter 6: Musculoskeletal Imaging',
      'Chapter 7: Neuroradiology',
      'Chapter 8: Pediatric Radiology',
    ],
    'Grainger & Allison\'s Diagnostic Radiology': [
      'Chapter 1: Imaging Techniques',
      'Chapter 2: Nuclear Medicine',
      'Chapter 3: Interventional Radiology',
      'Chapter 4: Oncologic Imaging',
      'Chapter 5: Emergency Radiology',
      'Chapter 6: Molecular Imaging',
      'Chapter 7: Artificial Intelligence in Radiology',
    ],
    'Miller\'s Anesthesia': [
      'Chapter 1: Basic Science',
      'Chapter 2: Preoperative Evaluation',
      'Chapter 3: Pharmacology',
      'Chapter 4: Airway Management',
      'Chapter 5: Regional Anesthesia',
      'Chapter 6: Critical Care',
      'Chapter 7: Pain Medicine',
      'Chapter 8: Pediatric Anesthesia',
    ],
    'Morgan & Mikhail\'s Clinical Anesthesiology': [
      'Chapter 1: Patient Monitoring',
      'Chapter 2: Cardiovascular Anesthesia',
      'Chapter 3: Neuroanesthesia',
      'Chapter 4: Obstetric Anesthesia',
      'Chapter 5: Geriatric Anesthesia',
      'Chapter 6: Ambulatory Anesthesia',
      'Chapter 7: Postoperative Care',
    ],
    'Tintinalli\'s Emergency Medicine': [
      'Chapter 1: Resuscitation',
      'Chapter 2: Cardiovascular Emergencies',
      'Chapter 3: Neurologic Emergencies',
      'Chapter 4: Trauma',
      'Chapter 5: Environmental Emergencies',
      'Chapter 6: Toxicology',
      'Chapter 7: Pediatric Emergencies',
      'Chapter 8: Disaster Medicine',
    ],
    'Rosen\'s Emergency Medicine': [
      'Chapter 1: Clinical Fundamentals',
      'Chapter 2: Critical Care',
      'Chapter 3: Infectious Emergencies',
      'Chapter 4: Shock',
      'Chapter 5: Wound Management',
      'Chapter 6: Orthopedic Emergencies',
      'Chapter 7: Procedural Skills',
    ],
    'Rakel & Rakel\'s Textbook of Family Medicine': [
      'Chapter 1: Primary Care',
      'Chapter 2: Preventive Medicine',
      'Chapter 3: Chronic Disease Management',
      'Chapter 4: Mental Health',
      'Chapter 5: Women\'s Health',
      'Chapter 6: Pediatric Care',
      'Chapter 7: Geriatric Medicine',
      'Chapter 8: Sports Medicine',
    ],
    'Taylor\'s Family Medicine': [
      'Chapter 1: Clinical Methods',
      'Chapter 2: Evidence-Based Medicine',
      'Chapter 3: Common Problems',
      'Chapter 4: Behavioral Health',
      'Chapter 5: Population Health',
      'Chapter 6: Office Procedures',
      'Chapter 7: Patient Education',
    ],
    'Nelson Textbook of Pediatrics': [
      'Chapter 1: Growth and Development',
      'Chapter 2: Nutrition',
      'Chapter 3: Infectious Diseases',
      'Chapter 4: Immunology',
      'Chapter 5: Pediatric Subspecialties',
      'Chapter 6: Critical Care',
      'Chapter 7: Neonatology',
      'Chapter 8: Adolescent Medicine',
    ],
    'Rudolph\'s Pediatrics': [
      'Chapter 1: Preventive Pediatrics',
      'Chapter 2: Emergency Care',
      'Chapter 3: Genetic Disorders',
      'Chapter 4: Endocrinology',
      'Chapter 5: Neurology',
      'Chapter 6: Cardiology',
      'Chapter 7: Gastroenterology',
    ],
  };

  static Map<String, List<String>> branchGuidelines = {
    'Kardiyoloji': [
      'ESC Guidelines 2023',
      'ACC/AHA Guidelines',
    ],
    'Nöroloji': [
      'AAN Guidelines',
      'European Academy of Neurology Guidelines',
    ],
    'Gastroenteroloji': [
      'EASL Guidelines',
      'ACG Guidelines',
      'AASLD Guidelines',
    ],
    'Endokrinoloji': [
      'ADA Standards of Care 2024',
      'Endocrine Society Guidelines',
    ],
    'Nefroloji': [
      'KDIGO Guidelines',
      'ERA-EDTA Guidelines',
    ],
    'Göğüs Hastalıkları': [
      'GOLD Guidelines',
      'ERS/ATS Guidelines',
    ],
    'Hematoloji': [
      'ASH Clinical Practice Guidelines',
      'NCCN Guidelines - Hematologic Malignancies',
    ],
    'Romatoloji': [
      'EULAR Recommendations',
      'ACR Guidelines',
    ],
    'Enfeksiyon Hastalıkları': [
      'IDSA Guidelines',
      'WHO Guidelines on Infectious Diseases',
    ],
    'Onkoloji': [
      'NCCN Guidelines',
      'ESMO Clinical Practice Guidelines',
    ],
    'Dermatoloji': [
      'AAD Guidelines',
      'EDF Guidelines',
    ],
    'Fizik Tedavi ve Rehabilitasyon': [
      'APTA Clinical Practice Guidelines',
      'ESPRM Guidelines',
    ],
    'Psikiyatri': [
      'APA Practice Guidelines',
      'NICE Mental Health Guidelines',
    ],
    'Genel Cerrahi': [
      'ACS Surgery Guidelines',
      'ERAS Guidelines',
    ],
    'Ortopedi': [
      'AAOS Clinical Practice Guidelines',
      'EFORT Guidelines',
    ],
    'Üroloji': [
      'EAU Guidelines',
      'AUA Guidelines',
    ],
    'Göz Hastalıkları': [
      'AAO Preferred Practice Patterns',
      'EURETINA Guidelines',
    ],
    'KBB': [
      'AAO-HNS Clinical Practice Guidelines',
      'EAONO Guidelines',
    ],
    'Kadın Hastalıkları ve Doğum': [
      'ACOG Practice Bulletins',
      'RCOG Guidelines',
    ],
    'Radyoloji': [
      'ACR Appropriateness Criteria',
      'ESR iGuide',
    ],
    'Anesteziyoloji': [
      'ASA Practice Parameters',
      'ESA Guidelines',
    ],
    'Acil Tıp': [
      'ACEP Clinical Policies',
      'EuSEM Guidelines',
    ],
    'Aile Hekimliği': [
      'AAFP Clinical Practice Guidelines',
      'WONCA Guidelines',
    ],
    'Çocuk Sağlığı ve Hastalıkları': [
      'AAP Clinical Practice Guidelines',
      'ESPGHAN Guidelines',
    ],
  };

  static Map<String, List<String>> guidelineChapters = {
    'ESC Guidelines 2023': [
      'Acute Coronary Syndromes',
      'Heart Failure Management',
      'Atrial Fibrillation',
      'Valvular Heart Disease',
      'Hypertension Management',
      'Cardiovascular Prevention',
      'Diabetes and Cardiovascular Disease',
      'Sports Cardiology',
    ],
    'ACC/AHA Guidelines': [
      'Primary Prevention',
      'Stable Ischemic Heart Disease',
      'Heart Failure',
      'Hypertension',
      'Cholesterol Management',
      'Lifestyle Modifications',
      'Risk Assessment',
      'Cardiac Device Therapy',
    ],
    'AAN Guidelines': [
      'Stroke Prevention',
      'Epilepsy Management',
      'Multiple Sclerosis Treatment',
      'Parkinson\'s Disease',
      'Headache Assessment and Treatment',
      'Dementia Care',
      'Neuropathy Diagnosis',
    ],
    'European Academy of Neurology Guidelines': [
      'Acute Stroke Management',
      'Chronic Headache',
      'Movement Disorders',
      'Neuroimmunology',
      'Sleep Disorders',
      'Neuro-oncology',
      'Neuromuscular Disorders',
    ],
    'EASL Guidelines': [
      'Cirrhosis Management',
      'Viral Hepatitis',
      'Alcoholic Liver Disease',
      'Non-alcoholic Fatty Liver Disease',
      'Portal Hypertension',
      'Hepatocellular Carcinoma',
      'Autoimmune Liver Disease',
    ],
    'ACG Guidelines': [
      'IBD Treatment',
      'Colorectal Cancer Screening',
      'GERD Management',
      'Peptic Ulcer Disease',
      'Celiac Disease',
      'Barrett\'s Esophagus',
      'Functional GI Disorders',
    ],
    'AASLD Guidelines': [
      'Hepatitis Treatment',
      'Cirrhosis Complications',
      'Liver Transplantation',
      'Hepatocellular Carcinoma',
      'Drug-induced Liver Injury',
      'Autoimmune Hepatitis',
      'Wilson Disease',
    ],
    'ADA Standards of Care 2024': [
      'Diabetes Management',
      'Cardiovascular Risk Management',
      'Microvascular Complications',
      'Glycemic Targets',
      'Pharmacologic Therapy',
      'Diabetes Technology',
      'Prevention of Type 2 Diabetes',
    ],
    'Endocrine Society Guidelines': [
      'Thyroid Disease',
      'Osteoporosis',
      'Pituitary Disorders',
      'Adrenal Insufficiency',
      'Gender Dysphoria',
      'Obesity Management',
      'Metabolic Bone Disease',
    ],
    'KDIGO Guidelines': [
      'CKD Evaluation and Management',
      'Acute Kidney Injury',
      'Glomerulonephritis',
      'Blood Pressure Management',
      'Diabetes in CKD',
      'Transplant Care',
      'Anemia Management',
    ],
    'ERA-EDTA Guidelines': [
      'Dialysis Adequacy',
      'Vascular Access',
      'Mineral Bone Disease',
      'Cardiovascular Disease in CKD',
      'Nutrition in CKD',
      'Transplantation',
      'Pediatric Nephrology',
    ],
    'GOLD Guidelines': [
      'COPD Management',
      'COPD Diagnosis and Assessment',
      'Prevention of COPD Exacerbations',
      'Management of Stable COPD',
      'Management of Exacerbations',
      'COPD and Comorbidities',
      'Pharmacologic Treatment',
    ],
    'ERS/ATS Guidelines': [
      'Asthma Management',
      'Severe Asthma',
      'Bronchiectasis',
      'Pulmonary Hypertension',
      'Sleep-Disordered Breathing',
      'Interstitial Lung Disease',
      'Respiratory Infections',
    ],
    'ASH Clinical Practice Guidelines': [
      'Hematologic Malignancies',
      'Venous Thromboembolism',
      'Immune Thrombocytopenia',
      'Sickle Cell Disease',
      'Anticoagulation Therapy',
      'von Willebrand Disease',
      'COVID-19 and Coagulopathy',
    ],
    'NCCN Guidelines - Hematologic Malignancies': [
      'Acute Myeloid Leukemia',
      'Chronic Lymphocytic Leukemia',
      'Multiple Myeloma',
      'Non-Hodgkin Lymphomas',
      'Hodgkin Lymphoma',
      'Myeloproliferative Neoplasms',
      'Myelodysplastic Syndromes',
    ],
    'EULAR Recommendations': [
      'Rheumatoid Arthritis',
      'Systemic Lupus Erythematosus',
      'Axial Spondyloarthritis',
      'Psoriatic Arthritis',
      'Giant Cell Arteritis',
      'Systemic Sclerosis',
      'Gout Management',
    ],
    'ACR Guidelines': [
      'Rheumatoid Arthritis',
      'Osteoarthritis',
      'Gout',
      'Vasculitis',
      'Juvenile Arthritis',
      'Glucocorticoid-Induced Osteoporosis',
      'Reproductive Health in Rheumatic Diseases',
    ],
    'IDSA Guidelines': [
      'Infectious Diseases',
      'Antimicrobial Stewardship',
      'COVID-19 Treatment',
      'Bacterial Infections',
      'Fungal Infections',
      'HIV/AIDS Management',
      'Vaccination Recommendations',
    ],
    'WHO Guidelines on Infectious Diseases': [
      'Infectious Diseases',
      'Global Health Security',
      'Emerging Infections',
      'Antimicrobial Resistance',
      'Tuberculosis Management',
      'HIV Treatment',
      'Tropical Diseases',
    ],
    'NCCN Guidelines': [
      'Breast Cancer',
      'Lung Cancer',
      'Colorectal Cancer',
      'Prostate Cancer',
      'Melanoma',
      'Head and Neck Cancers',
      'Supportive Care',
    ],
    'ESMO Clinical Practice Guidelines': [
      'Clinical Trial Design',
      'Precision Medicine',
      'Immunotherapy',
      'Cancer Prevention',
      'Palliative Care',
      'Survivorship',
      'Quality of Life',
    ],
    'AAD Guidelines': [
      'Acne Management',
      'Psoriasis Treatment',
      'Atopic Dermatitis',
      'Skin Cancer Prevention',
      'Hair Disorders',
      'Cosmetic Dermatology',
      'Wound Care',
    ],
    'EDF Guidelines': [
      'Melanoma Management',
      'Sexually Transmitted Infections',
      'Autoimmune Diseases',
      'Pediatric Dermatology',
      'Allergic Conditions',
      'Nail Disorders',
      'Phototherapy',
    ],
    'APTA Clinical Practice Guidelines': [
      'Low Back Pain',
      'Neck Pain',
      'Balance and Falls',
      'Post-operative Rehabilitation',
      'Neurological Rehabilitation',
      'Pediatric Therapy',
      'Geriatric Rehabilitation',
    ],
    'ESPRM Guidelines': [
      'Stroke Rehabilitation',
      'Spinal Cord Injury',
      'Musculoskeletal Conditions',
      'Cardiac Rehabilitation',
      'Amputee Rehabilitation',
      'Pain Management',
      'Occupational Rehabilitation',
    ],
    'APA Practice Guidelines': [
      'Major Depression',
      'Bipolar Disorder',
      'Schizophrenia',
      'Anxiety Disorders',
      'Substance Use Disorders',
      'PTSD',
      'Eating Disorders',
    ],
    'NICE Mental Health Guidelines': [
      'Depression Management',
      'Psychosis Treatment',
      'OCD Management',
      'Personality Disorders',
      'Child Mental Health',
      'Dementia Care',
      'Self-harm Prevention',
    ],
    'ACS Surgery Guidelines': [
      'Preoperative Assessment',
      'Surgical Site Infections',
      'Postoperative Care',
      'Emergency Surgery',
      'Minimally Invasive Surgery',
      'Cancer Surgery',
      'Trauma Surgery',
    ],
    'ERAS Guidelines': [
      'Colorectal Surgery',
      'Gynecologic Surgery',
      'Bariatric Surgery',
      'Liver Surgery',
      'Pancreatic Surgery',
      'Thoracic Surgery',
      'Enhanced Recovery Protocols',
    ],
    'AAOS Clinical Practice Guidelines': [
      'Hip Fractures',
      'Knee Osteoarthritis',
      'Rotator Cuff Problems',
      'Carpal Tunnel Syndrome',
      'Ankle Sprains',
      'Vertebral Compression Fractures',
      'Prevention of Surgical Site Infections',
    ],
    'EFORT Guidelines': [
      'Joint Replacement',
      'Sports Injuries',
      'Bone Tumors',
      'Pediatric Orthopedics',
      'Trauma Management',
      'Arthroscopy',
      'Musculoskeletal Infections',
    ],
    'EAU Guidelines': [
      'Prostate Cancer',
      'Bladder Cancer',
      'Kidney Cancer',
      'Male Infertility',
      'Urolithiasis',
      'BPH Management',
      'Urinary Incontinence',
    ],
    'AUA Guidelines': [
      'Erectile Dysfunction',
      'Overactive Bladder',
      'Prostate Cancer Screening',
      'Testosterone Therapy',
      'Surgical Management',
      'Pediatric Urology',
      'Urologic Trauma',
    ],
    'AAO Preferred Practice Patterns': [
      'Cataract Surgery',
      'Glaucoma Management',
      'Diabetic Retinopathy',
      'Age-related Macular Degeneration',
      'Refractive Errors',
      'Amblyopia',
      'Ocular Surface Disease',
    ],
    'EURETINA Guidelines': [
      'Retinal Vein Occlusion',
      'Macular Degeneration',
      'Diabetic Macular Edema',
      'Retinal Detachment',
      'Inherited Retinal Disease',
      'Inflammatory Eye Disease',
      'Retinal Imaging',
    ],
    'AAO-HNS Clinical Practice Guidelines': [
      'Tonsillectomy',
      'Otitis Media',
      'Sinusitis',
      'Hearing Loss',
      'Tinnitus',
      'Voice Disorders',
      'Sleep Apnea',
    ],
    'EAONO Guidelines': [
      'Chronic Otitis Media',
      'Vestibular Disorders',
      'Cochlear Implants',
      'Facial Nerve Disorders',
      'Skull Base Surgery',
      'Otosclerosis',
      'Ménière\'s Disease',
    ],
    'ACOG Practice Bulletins': [
      'Prenatal Care',
      'Labor Management',
      'Cesarean Delivery',
      'Postpartum Care',
      'Contraception',
      'Gynecologic Surgery',
      'Menopause Management',
    ],
    'RCOG Guidelines': [
      'Antenatal Care',
      'Intrapartum Care',
      'Maternal Medicine',
      'Fertility Treatment',
      'Gynecologic Oncology',
      'Early Pregnancy Loss',
      'Fetal Medicine',
    ],
    'ACR Appropriateness Criteria': [
      'Neuroimaging',
      'Chest Imaging',
      'Cardiovascular Imaging',
      'Musculoskeletal Imaging',
      'Oncologic Imaging',
      'Pediatric Imaging',
      'Interventional Procedures',
    ],
    'ESR iGuide': [
      'CT Protocols',
      'MRI Safety',
      'Radiation Protection',
      'Contrast Media',
      'Emergency Radiology',
      'Women\'s Imaging',
      'Nuclear Medicine',
    ],
    'ASA Practice Parameters': [
      'Preoperative Fasting',
      'Difficult Airway',
      'Perioperative Blood Management',
      'Postoperative Pain',
      'Monitored Anesthesia Care',
      'Regional Anesthesia',
      'Obstetric Anesthesia',
    ],
    'ESA Guidelines': [
      'Preoperative Evaluation',
      'Perioperative Care',
      'Airway Management',
      'Local Anesthetics',
      'Day Surgery',
      'Critical Emergency',
      'Pediatric Anesthesia',
    ],
    'ACEP Clinical Policies': [
      'Chest Pain',
      'Head Trauma',
      'Sepsis',
      'Acute Stroke',
      'Pain Management',
      'Procedural Sedation',
      'Pediatric Fever',
    ],
    'EuSEM Guidelines': [
      'Triage',
      'Resuscitation',
      'Trauma Care',
      'Toxicology',
      'Disaster Medicine',
      'Emergency Ultrasound',
      'Prehospital Care',
    ],
    'AAFP Clinical Practice Guidelines': [
      'Hypertension Management',
      'Diabetes Care',
      'Depression Screening',
      'Cancer Prevention',
      'Immunizations',
      'Chronic Pain',
      'End-of-life Care',
    ],
    'WONCA Guidelines': [
      'Primary Prevention',
      'Chronic Disease Care',
      'Mental Health',
      'Women\'s Health',
      'Child Health',
      'Elderly Care',
      'Community Medicine',
    ],
    'AAP Clinical Practice Guidelines': [
      'Well-Child Care',
      'Immunization Schedule',
      'ADHD Management',
      'Autism Spectrum Disorders',
      'Respiratory Infections',
      'Growth Assessment',
      'Adolescent Health',
    ],
    'ESPGHAN Guidelines': [
      'Nutrition',
      'Celiac Disease',
      'IBD in Children',
      'Liver Disorders',
      'GI Motility',
      'Food Allergies',
      'Metabolic Disorders',
    ],
  };
}
